### ISSUE TITLE
Request: Publish a new release with the latest changes

### ISSUE THREAD

**Issue by JakeChampion** [mathiasbynens/Array.of#11]
Thanks for reviewing my pull requests and merging them. I was wondering when a new release to NPMJS' registry would be published, it isn't an urgent issue, please don't feel rushed with it :-)

It seems that some other bugs have been fixed which have not been released, [here is the difference since the last release](https://github.com/mathiasbynens/Array.of/compare/f185495cb3c2216ff4ae74bd11ad89e74032df21...master) - I believe the only release that has been made is from the project's [initial commit](https://github.com/mathiasbynens/Array.of/commit/f185495cb3c2216ff4ae74bd11ad89e74032df21).

**Comment by mathiasbynens** [comment]
@ljharb I just made you owner of this package on npm. (Why hadn’t I done this before?!) Will you do the honors? :)

**Comment by ljharb** [comment]
@mathiasbynens Thanks! Happily.

**Comment by ljharb** [comment]
Published as v0.1.1 with linting and a changelog :-)
