### ISSUE TITLE
pollutes builtin with properties

### ISSUE THREAD

**Issue by jdalton** [mathiasbynens/Array.of#12]
When Array.of exists it will be used as `polyfill` and then extended:
https://github.com/mathiasbynens/Array.of/blob/master/index.js#L11
```js
define(polyfill, {
	'getPolyfill': getPolyfill,
	'implementation': implementation,
	'shim': shim
});
```
other like packages use a wrapper like `bound` or other to avoid augmenting the original builtin.

**Comment by ljharb** [comment]
Thanks! I also added some tests to https://npmjs.com/@es-shims/api to catch this for other packages.

**Comment by jdalton** [comment]
Thank you @ljharb! ❤️ the added tests!
